import type { LegalDoc } from '@/components/legal-page';
import { COMPANY } from './company';

const UPDATED_ISO = '2026-05-23';
const UPDATED_DISPLAY = 'May 23, 2026';

export const PRIVACY: LegalDoc = {
  title: 'Privacy Policy',
  updatedISO: UPDATED_ISO,
  updatedDisplay: UPDATED_DISPLAY,
  intro: `This policy covers the corporate website at ${COMPANY.domain}. Each ${COMPANY.shortName} product (Velocity, Academy, Andiamo, Pathfinder) has its own privacy policy at its own subdomain governing data collected by that product.`,
  sections: [
    {
      heading: 'What this site collects',
      body: [
        `This site is mostly static. We do not run third-party analytics, advertising trackers, or session-replay tooling. Standard web-server logs (IP, user-agent, requested URL, timestamp) are retained for 30 days for security and debugging.`,
        `If you submit the issue-intake form at /report, we collect the email address you provide and the contents of your message so we can respond. Submissions are stored in our support inbox (${COMPANY.supportEmail}) and treated like any other email.`,
      ],
    },
    {
      heading: 'Cookies',
      body: `This site does not set any cookies of its own. It also does not embed cross-site trackers. See our Cookie Policy for details.`,
    },
    {
      heading: 'Service providers',
      body: `We use Postmark to deliver the email generated by the issue-intake form. Postmark sees the email address and message body for the duration of delivery. We use Microsoft Azure to host this site; Azure sees standard request metadata.`,
    },
    {
      heading: 'Your rights',
      body: `Email ${COMPANY.helloEmail} for access, deletion, or correction requests for data this site holds about you. We respond within 30 days. For data held by an individual product, contact that product directly.`,
    },
    {
      heading: 'Children',
      body: `This site is not directed to children under 13. We do not knowingly collect data from children. Academy, our learning product, has its own policy that addresses students.`,
    },
    {
      heading: 'Changes',
      body: `We version this policy by date. The current version is shown at the top of the page.`,
    },
    {
      heading: 'Contact',
      body: `${COMPANY.legalName}, ${COMPANY.location}. Email: ${COMPANY.helloEmail}.`,
    },
  ],
};

export const TERMS: LegalDoc = {
  title: 'Terms of Use',
  updatedISO: UPDATED_ISO,
  updatedDisplay: UPDATED_DISPLAY,
  intro: `These terms govern access to the corporate website at ${COMPANY.domain}. Use of any individual ${COMPANY.shortName} product is governed by that product's own terms.`,
  sections: [
    {
      heading: 'Acceptance',
      body: `By accessing this site you agree to these terms. If you don't agree, please don't use the site.`,
    },
    {
      heading: 'Content',
      body: `Content on this site is published for general information about ${COMPANY.legalName} and its products. We try to keep it accurate and current but make no representations or warranties about completeness, accuracy, or fitness for any particular purpose.`,
    },
    {
      heading: 'Intellectual property',
      body: `Trademarks, logos, the site design, and copy are owned by ${COMPANY.legalName} unless attributed otherwise. The Andiamo mobility settlement architecture is protected by US Patent 12,567,119 B1.`,
    },
    {
      heading: 'Acceptable use',
      body: [
        `Don't probe, scan, or attempt to breach the security of this site or its infrastructure without prior written permission. Good-faith security research is welcome — use the /report form first.`,
        `Don't scrape the site for the purpose of training machine-learning models without prior written permission.`,
      ],
    },
    {
      heading: 'No warranty',
      body: `The site is provided "as is" without warranty of any kind, express or implied.`,
    },
    {
      heading: 'Limitation of liability',
      body: `To the maximum extent permitted by law, ${COMPANY.legalName} is not liable for any indirect, incidental, special, or consequential damages arising from use of this site.`,
    },
    {
      heading: 'Governing law',
      body: `These terms are governed by the laws of the State of Delaware, USA, without regard to its conflict of law provisions.`,
    },
    {
      heading: 'Changes',
      body: `We version these terms by date. The current version is shown at the top of the page.`,
    },
    {
      heading: 'Contact',
      body: `${COMPANY.legalName}, ${COMPANY.location}. Email: ${COMPANY.helloEmail}.`,
    },
  ],
};

export const COOKIES: LegalDoc = {
  title: 'Cookie Policy',
  updatedISO: UPDATED_ISO,
  updatedDisplay: UPDATED_DISPLAY,
  intro: `This site does not set cookies. This policy exists to document that fact and to explain what would change that.`,
  sections: [
    {
      heading: 'What we set',
      body: `Nothing. No first-party cookies. No analytics. No advertising trackers. No social-media embeds that would set cookies.`,
    },
    {
      heading: 'What our products set',
      body: `Velocity, Academy, Andiamo, and Pathfinder each run on their own subdomain or distribution channel and have their own cookie practices. See each product's privacy/cookie policy for specifics.`,
    },
    {
      heading: 'If that changes',
      body: `If we ever add analytics or other cookie-setting tools to this site, we will (1) update this policy with the date and the list of cookies, and (2) require explicit consent before setting any non-essential cookie.`,
    },
    {
      heading: 'Contact',
      body: `Questions: ${COMPANY.helloEmail}.`,
    },
  ],
};
